# Generated by Django 6.0.5 on 2026-05-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_data',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_email', models.EmailField(max_length=55)),
                ('emp_salary', models.IntegerField()),
                ('emp_phone', models.IntegerField(max_length=10)),
                ('emp_address', models.TextField()),
                ('emp_joindate', models.DateField()),
                ('emp_gender', models.CharField(max_length=10)),
                ('emp_age', models.IntegerField()),
                ('emp_dept', models.CharField(max_length=30)),
                ('emp_experience', models.IntegerField()),
            ],
        ),
    ]
