# Generated by Django 6.0.5 on 2026-05-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_data',
            name='emp_phone',
            field=models.IntegerField(),
        ),
    ]
