# Generated by Django 6.0.5 on 2026-05-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
